/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/common/AppButton.vue')['default']
    AppCard: typeof import('./src/components/common/AppCard.vue')['default']
    AppEmpty: typeof import('./src/components/common/AppEmpty.vue')['default']
    AppInput: typeof import('./src/components/common/AppInput.vue')['default']
    AppSelect: typeof import('./src/components/common/AppSelect.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    MobileTabBar: typeof import('./src/components/nav/MobileTabBar.vue')['default']
    QuestionCard: typeof import('./src/components/exercise/QuestionCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopNavBar: typeof import('./src/components/nav/TopNavBar.vue')['default']
  }
}
